from __future__ import annotations

import json
import logging
import os
import time
from typing import Optional

from app.models import ClientProfile, WorkoutWeek
from app.adapters.llm.openrouter import LLMClient, OpenRouterClient

logger = logging.getLogger(__name__)


class FlashCommunicationService:
    """
    Wraps LLM calls for coaching message generation and coach-edit application.

    Can be constructed with an explicit LLMClient (e.g. from Container) or will
    fall back to building its own OpenRouterClient from environment variables so
    that bot.py can keep calling ``FlashCommunicationService()`` without changes.
    """

    def __init__(self, llm_client: Optional[LLMClient] = None) -> None:
        if llm_client is not None:
            self._llm = llm_client
        else:
            # Backward-compatible fallback: read credentials from env
            from dotenv import load_dotenv
            load_dotenv()
            api_key = os.getenv("OPENROUTER_API_KEY", "")
            base_url = os.getenv("OPENROUTER_BASE_URL", "https://openrouter.ai/api/v1")
            model_id = os.getenv("LLM_MODEL_ID", "google/gemini-2.5-flash")
            self._llm = OpenRouterClient(api_key=api_key, base_url=base_url, model_id=model_id)

    def generate_coaching_message(self, profile: ClientProfile, workout: WorkoutWeek) -> str:
        system_instruction = (
            "You are an elite strength and conditioning coach. Your job is to take a strict JSON "
            "workout plan generated by our biomechanics engine and format it into a highly motivating, "
            "easy-to-read weekly email for the client.\n\n"
            "CRITICAL RULES:\n"
            "1. DO NOT change, add, or remove any exercises, sets, or reps from the provided JSON. "
            "The engine's word is final.\n"
            "2. Briefly explain *why* this specific plan makes sense for their goals, experience level, "
            "and listed limitations.\n"
            "3. Use a professional, encouraging tone.\n"
            "4. Format the output to be highly readable on a mobile messaging app. Use Telegram-compatible "
            "HTML or basic Markdown (avoid complex Markdown tables). Use emojis appropriately."
        )

        prompt = (
            f"CLIENT PROFILE:\n{profile.model_dump_json(indent=2)}\n\n"
            f"GENERATED WORKOUT PLAN:\n{workout.model_dump_json(indent=2)}\n\n"
            "Please draft the coaching email for this client."
        )

        for attempt in range(3):
            try:
                response = self._llm.complete(system=system_instruction, user=prompt, temperature=0.4)
                break
            except Exception as e:
                if attempt == 2:
                    raise
                logger.warning("LLM call failed (attempt %d/3): %s", attempt + 1, e)
                time.sleep(2 ** attempt)
        return response

    def generate_exercise_tips(self, exercise_name: str, experience_level: str, avatar: str) -> str:
        """Generate a concise form/technique breakdown for an exercise."""
        system_instruction = (
            "You are an elite strength and conditioning coach specialising in technique coaching. "
            "Give a concise but complete technique breakdown. Use Telegram-compatible Markdown. "
            "Structure your reply with three short sections: "
            "**Setup** (2-3 bullets), **Execution** (3-4 bullets), **Common Errors** (2-3 bullets). "
            "Keep the whole reply under 300 words."
        )
        prompt = (
            f"Exercise: {exercise_name}\n"
            f"Client level: {experience_level}\n"
            f"Training style: {avatar}\n\n"
            "Write the technique breakdown for this client."
        )
        return self._llm.complete(system=system_instruction, user=prompt, temperature=0.3)

    def draft_qa_answer(self, question: str, profile: "ClientProfile",
                        latest_workout: "WorkoutWeek | None") -> str:
        """Draft a RECOMMENDED answer to a client's question, grounded in their profile and
        current plan. This is a DRAFT for the human coach to review — never sent as-is."""
        system_instruction = (
            "You are an elite strength & conditioning coach drafting a SUGGESTED reply to a "
            "client's question, for your head coach to review before it is sent. Ground the "
            "answer in the client's profile and current plan. Be concise (2-5 sentences), "
            "specific, and safe; if the question needs medical or in-person assessment, say so "
            "rather than guessing. Plain text suitable for a messaging app; no preamble."
        )
        plan_section = (latest_workout.model_dump_json(indent=2)
                        if latest_workout is not None else "(no active plan yet)")
        prompt = (
            f"CLIENT PROFILE:\n{profile.model_dump_json(indent=2)}\n\n"
            f"CURRENT PLAN:\n{plan_section}\n\n"
            f"CLIENT QUESTION:\n{question}\n\n"
            "Draft the suggested answer."
        )
        for attempt in range(3):
            try:
                return self._llm.complete(system=system_instruction, user=prompt, temperature=0.4)
            except Exception as e:
                if attempt == 2:
                    raise
                logger.warning("draft_qa_answer LLM call failed (attempt %d/3): %s", attempt + 1, e)
                time.sleep(2 ** attempt)

    def apply_coach_edits(self, workout_json: str, coach_feedback: str) -> str:
        system_instruction = (
            "You are a programmatic JSON manipulator acting as the backbone of a deterministic coaching app.\n"
            "You will be provided a strict JSON payload representing a week's workout plan, and a string of "
            "feedback from the Head Coach.\n\n"
            "CRITICAL RULES:\n"
            "1. Return strictly valid JSON containing the updated WorkoutWeek struct, and absolutely nothing "
            "else. No markdown formatting blocks (no ```json ... ```, just the raw JSON object).\n"
            "2. Apply the coach's feedback logically to the JSON.\n"
            "3. Do not drop properties unless explicitly told to."
        )

        prompt = (
            f"CURRENT WORKOUT JSON:\n{workout_json}\n\n"
            f"COACH FEEDBACK:\n{coach_feedback}"
        )

        for attempt in range(3):
            try:
                content = self._llm.complete(system=system_instruction, user=prompt, temperature=0.1)
                break
            except Exception as e:
                if attempt == 2:
                    raise
                logger.warning("LLM call failed (attempt %d/3): %s", attempt + 1, e)
                time.sleep(2 ** attempt)

        # Guard against markdown wrapping from models that ignore instructions
        content = content.strip()
        if content.startswith("```json"):
            content = content[7:]
        if content.startswith("```"):
            content = content[3:]
        if content.endswith("```"):
            content = content[:-3]

        content = content.strip()

        try:
            json.loads(content)  # validate JSON before returning
        except json.JSONDecodeError as e:
            raise ValueError(f"LLM returned invalid JSON: {e}\nContent: {content[:200]}")

        # Validate the edited payload is a structurally-valid WorkoutWeek before it
        # can overwrite a live plan — a malformed LLM response must not corrupt it.
        from app.models import WorkoutWeek
        try:
            WorkoutWeek.model_validate_json(content)
        except Exception as e:
            raise ValueError(f"LLM edit is not a valid WorkoutWeek: {e}\nContent: {content[:200]}")

        return content
